import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import Timer from "@/app/_components/timer";
import { TRPCReactProvider } from "@/trpc/react";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <nav className="sticky">
            <div className="flex items-center justify-between bg-white p-4">
              <div className="flex items-center space-x-4">
                <Link href="/" className="text-2xl font-bold">
                  Home
                </Link>
              </div>
              <div className="flex items-center space-x-4">
                <Link
                  href="/about"
                  className="text-sm font-medium text-gray-900"
                >
                  About
                </Link>
              </div>
            </div>
          </nav>
          <Timer />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
